#! /usr/bin/env python3


from subprocess import CalledProcessError, run, PIPE, DEVNULL
from sys import argv, exit, stderr, stdout


def main():
    if len(argv) == 1:
        print('usage: %s: [COMMAND] [ARGS]...' % argv[0], file=stderr)
        exit(1)

    try:
        run(argv[1:], stdin=DEVNULL, stdout=PIPE, stderr=PIPE, check=True)
        exit(0)
    except CalledProcessError as e:
        print(e.stdout.decode(), file=stdout, flush=True)
        print(e.stderr.decode(), file=stderr, flush=True)
        exit(e.returncode)


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass
